// <auto-generated />
using System;
using CouncilAgendaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CouncilAgendaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513224742_AddInvitations")]
    partial class AddInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CouncilAgendaApi.Models.AgendaAttendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Attending")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.HasIndex("MemberId");

                    b.ToTable("AgendaAttendees");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.AgendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HandbookSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("TopicBacklogId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HandbookSectionId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("TopicBacklogId");

                    b.ToTable("AgendaItems");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.AgendaNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AgendaItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByClerkUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItemId");

                    b.HasIndex("MeetingId");

                    b.ToTable("AgendaNotes");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AgendaItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItemId");

                    b.HasIndex("MeetingId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AgendaItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgendaItemId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.HandbookSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Chapter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MinistryAreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MinistryAreaId");

                    b.ToTable("HandbookSections");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClerkInvitationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("InvitedByClerkUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.InvitationOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("InvitationOrganizations");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AgendaGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool>("AgendaPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GoogleDocUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Calling")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.MinistryArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("LastFocused")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MinistryAreas");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("ConductingRotates")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrgType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.OrganizationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MeetingDay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MeetingDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("MeetingTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WeekOfMonth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("OrganizationSettings");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.RecurringResponsibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LastCheckedByClerkUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastCheckedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LcrUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaxWeeks")
                        .HasColumnType("integer");

                    b.Property<int>("MinWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("OrgTypeScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("RecurringResponsibilities");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.ResponsibilityCheckin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CheckedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CheckedByClerkUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsibilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibilityId");

                    b.ToTable("ResponsibilityCheckins");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.RotationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RotationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("RotationLogs");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.TopicBacklogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("MinistryAreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MinistryAreaId");

                    b.ToTable("TopicBacklogItems");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.UserOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("UserOrganizations");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.AgendaAttendee", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.Meeting", "Meeting")
                        .WithMany("Attendees")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CouncilAgendaApi.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.AgendaItem", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.HandbookSection", "HandbookSection")
                        .WithMany()
                        .HasForeignKey("HandbookSectionId");

                    b.HasOne("CouncilAgendaApi.Models.Meeting", "Meeting")
                        .WithMany("AgendaItems")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CouncilAgendaApi.Models.TopicBacklogItem", "TopicBacklogItem")
                        .WithMany()
                        .HasForeignKey("TopicBacklogId");

                    b.Navigation("HandbookSection");

                    b.Navigation("Meeting");

                    b.Navigation("TopicBacklogItem");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.AgendaNote", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.AgendaItem", "AgendaItem")
                        .WithMany()
                        .HasForeignKey("AgendaItemId");

                    b.HasOne("CouncilAgendaApi.Models.Meeting", "Meeting")
                        .WithMany("Notes")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaItem");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Assignment", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.AgendaItem", "AgendaItem")
                        .WithMany()
                        .HasForeignKey("AgendaItemId");

                    b.HasOne("CouncilAgendaApi.Models.Meeting", "Meeting")
                        .WithMany("Assignments")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CouncilAgendaApi.Models.Member", "Owner")
                        .WithMany("Assignments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaItem");

                    b.Navigation("Meeting");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Attachment", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.AgendaItem", "AgendaItem")
                        .WithMany()
                        .HasForeignKey("AgendaItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CouncilAgendaApi.Models.Organization", "Organization")
                        .WithMany("Attachments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgendaItem");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.HandbookSection", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.MinistryArea", "MinistryArea")
                        .WithMany("HandbookSections")
                        .HasForeignKey("MinistryAreaId");

                    b.Navigation("MinistryArea");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.InvitationOrganization", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.Invitation", "Invitation")
                        .WithMany("Organizations")
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CouncilAgendaApi.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitation");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Meeting", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.Organization", "Organization")
                        .WithMany("Meetings")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Member", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.OrganizationSettings", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.Organization", "Organization")
                        .WithOne()
                        .HasForeignKey("CouncilAgendaApi.Models.OrganizationSettings", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.RecurringResponsibility", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.Organization", "Organization")
                        .WithMany("RecurringResponsibilities")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.ResponsibilityCheckin", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.RecurringResponsibility", "Responsibility")
                        .WithMany("Checkins")
                        .HasForeignKey("ResponsibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsibility");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.RotationLog", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.Member", "Member")
                        .WithMany("RotationLogs")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.TopicBacklogItem", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.MinistryArea", "MinistryArea")
                        .WithMany("TopicBacklogItems")
                        .HasForeignKey("MinistryAreaId");

                    b.Navigation("MinistryArea");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.UserOrganization", b =>
                {
                    b.HasOne("CouncilAgendaApi.Models.Organization", "Organization")
                        .WithMany("UserOrganizations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Invitation", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Meeting", b =>
                {
                    b.Navigation("AgendaItems");

                    b.Navigation("Assignments");

                    b.Navigation("Attendees");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Member", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("RotationLogs");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.MinistryArea", b =>
                {
                    b.Navigation("HandbookSections");

                    b.Navigation("TopicBacklogItems");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.Organization", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Meetings");

                    b.Navigation("Members");

                    b.Navigation("RecurringResponsibilities");

                    b.Navigation("UserOrganizations");
                });

            modelBuilder.Entity("CouncilAgendaApi.Models.RecurringResponsibility", b =>
                {
                    b.Navigation("Checkins");
                });
#pragma warning restore 612, 618
        }
    }
}
